---
title: "got"
author: "Julie"
date: "2026-05-19"
output: html_document
---


```{r}
library(tidyverse)
library(tidytext)
library(pdftools)
library(here)
library(ggwordcloud)
library(stringr)
```



## Import PDF

```{r}
got_path <- here("data", "got.pdf")

got_text <- pdf_text(got_path)
```


## Wrangle text

```{r split-lines}
got_df <- data.frame(got_text) %>% 
  mutate(text_full = str_split(got_text, pattern = '\n')) %>% 
  unnest(text_full) %>% 
  mutate(text_full = str_trim(text_full))
```


## Tokenize words

```{r tokenize}
got_tokens <- got_df %>% 
  unnest_tokens(word, text_full)
```



## Remove stop words

```{r stopwords}
got_stop <- got_tokens %>% 
  anti_join(stop_words)
```


## NRC sentiment analysis

```{r bind-nrc}
got_nrc <- got_stop %>% 
  inner_join(get_sentiments("nrc"))
```



## Count emotions

```{r count-nrc}
got_nrc_n <- got_nrc %>% 
  count(sentiment, sort = TRUE)
```



## Emotion visualization

```{r plot-nrc}
ggplot(data = got_nrc_n,
       aes(x = sentiment,
           y = n)) +
  geom_col(aes(fill = sentiment)) +
  theme_bw()
```



